import { api } from '../api';
import { stripParentheticals } from '../../../shared/text';
import type { IpaAudioRef } from '../../../shared/ipa/games';

// Plays a word or sentence. Audio stored in (or generated by) the backend is
// preferred; when none is available the browser's on-device speech synthesis
// is used.

const urls = new Map<string, Promise<string | null>>();
let current: HTMLAudioElement | null = null;

function fetchAudioUrl(target: string, text: string): Promise<string | null> {
  return fetchBlobUrl(api.audioUrl(target, text));
}

// Audio from the backend as an object URL (cached); null when there is none.
function fetchBlobUrl(key: string): Promise<string | null> {
  let pending = urls.get(key);
  if (!pending) {
    pending = fetch(key)
      .then(async (response) => (response.status === 200 ? URL.createObjectURL(await response.blob()) : null))
      .catch(() => null);
    urls.set(key, pending);
    if (urls.size > 300) {
      const oldest = urls.keys().next().value;
      if (oldest !== undefined) {
        void urls.get(oldest)?.then((url) => url && URL.revokeObjectURL(url));
        urls.delete(oldest);
      }
    }
    // A failed generation is retried next time.
    void pending.then((url) => {
      if (!url) urls.delete(key);
    });
  }
  return pending;
}

// Forgets the audio fetched so far, e.g. after recordings were regenerated.
export function clearAudioCache(): void {
  const playing = current?.src;
  for (const pending of urls.values()) void pending.then((url) => url && url !== playing && URL.revokeObjectURL(url));
  urls.clear();
}

export function prefetchAudio(target: string, text: string): void {
  const clean = stripParentheticals(text);
  if (clean) void fetchAudioUrl(target, clean);
}

export function stopAudio(): void {
  current?.pause();
  current = null;
  if ('speechSynthesis' in window) window.speechSynthesis.cancel();
}

export function browserVoices(): SpeechSynthesisVoice[] {
  return 'speechSynthesis' in window ? window.speechSynthesis.getVoices() : [];
}

function pickVoice(locale: string, voiceName: string): SpeechSynthesisVoice | undefined {
  const voices = browserVoices();
  if (voiceName) {
    const named = voices.find((voice) => voice.name === voiceName);
    if (named) return named;
  }
  const lower = locale.toLowerCase();
  const language = lower.split('-')[0];
  return (
    voices.find((voice) => voice.lang.toLowerCase() === lower) ??
    voices.find((voice) => voice.lang.toLowerCase().replace('_', '-').startsWith(`${language}-`)) ??
    voices.find((voice) => voice.lang.toLowerCase() === language)
  );
}

export function speakWithBrowser(text: string, locale: string, voiceName = '', rate = 1): Promise<void> {
  return new Promise((resolve) => {
    if (!('speechSynthesis' in window)) {
      resolve();
      return;
    }
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = locale;
    utterance.rate = rate;
    const voice = pickVoice(locale, voiceName);
    if (voice) utterance.voice = voice;
    utterance.onend = () => resolve();
    utterance.onerror = () => resolve();
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  });
}

export interface VoiceOptions {
  locale: string;
  voice?: string;
  rate?: number;
}

export async function playText(target: string, text: string, options: VoiceOptions): Promise<void> {
  // Notes in parentheses are for reading only.
  const clean = stripParentheticals(text);
  if (!clean) return;
  stopAudio();
  const url = await fetchAudioUrl(target, clean);
  // Autoplay blocked or unsupported format: fall back to speech synthesis.
  if (url && (await playObjectUrl(url, options.rate ?? 1))) return;
  await speakWithBrowser(clean, options.locale, options.voice, options.rate);
}

// Plays until the end (or until stopped); false when it cannot be played.
async function playObjectUrl(url: string, rate: number): Promise<boolean> {
  const audio = new Audio(url);
  audio.playbackRate = rate;
  current = audio;
  try {
    await audio.play();
    await new Promise<void>((resolve) => {
      audio.onended = () => resolve();
      audio.onpause = () => resolve();
    });
    return true;
  } catch {
    return false;
  }
}

// Pronunciation mode: a sound on its own or a word. Words without a stored
// recording are spoken by the device; false when a sound has no recording.
export async function playIpa(ref: IpaAudioRef, rate = 1): Promise<boolean> {
  stopAudio();
  const url = await fetchBlobUrl(api.ipaAudioUrl(ref));
  if (url && (await playObjectUrl(url, rate))) return true;
  if (ref.kind === 'sound') return false;
  await speakWithBrowser(ref.text, ref.locale, '', rate);
  return true;
}

export function prefetchIpa(ref: IpaAudioRef): void {
  void fetchBlobUrl(api.ipaAudioUrl(ref));
}

// Plays one stored recording (lists of recordings with their sources).
export function playRecording(url: string): void {
  stopAudio();
  current = new Audio(url);
  void current.play().catch(() => undefined);
}

// Voices load asynchronously in some browsers.
if ('speechSynthesis' in window) {
  window.speechSynthesis.getVoices();
}
