import { api } from '../api';

// Plays a word or sentence. Audio stored in (or generated by) the backend is
// preferred; when none is available the browser's on-device speech synthesis
// is used.

const urls = new Map<string, Promise<string | null>>();
let current: HTMLAudioElement | null = null;

function cacheKey(target: string, text: string): string {
  return `${target}\u0000${text}`;
}

function fetchAudioUrl(target: string, text: string): Promise<string | null> {
  const key = cacheKey(target, text);
  let pending = urls.get(key);
  if (!pending) {
    pending = fetch(api.audioUrl(target, text))
      .then(async (response) => (response.status === 200 ? URL.createObjectURL(await response.blob()) : null))
      .catch(() => null);
    urls.set(key, pending);
    if (urls.size > 300) {
      const oldest = urls.keys().next().value;
      if (oldest !== undefined) {
        void urls.get(oldest)?.then((url) => url && URL.revokeObjectURL(url));
        urls.delete(oldest);
      }
    }
    // A failed generation is retried next time.
    void pending.then((url) => {
      if (!url) urls.delete(key);
    });
  }
  return pending;
}

export function prefetchAudio(target: string, text: string): void {
  if (text.trim()) void fetchAudioUrl(target, text.trim());
}

export function stopAudio(): void {
  current?.pause();
  current = null;
  if ('speechSynthesis' in window) window.speechSynthesis.cancel();
}

export function browserVoices(): SpeechSynthesisVoice[] {
  return 'speechSynthesis' in window ? window.speechSynthesis.getVoices() : [];
}

function pickVoice(locale: string, voiceName: string): SpeechSynthesisVoice | undefined {
  const voices = browserVoices();
  if (voiceName) {
    const named = voices.find((voice) => voice.name === voiceName);
    if (named) return named;
  }
  const lower = locale.toLowerCase();
  const language = lower.split('-')[0];
  return (
    voices.find((voice) => voice.lang.toLowerCase() === lower) ??
    voices.find((voice) => voice.lang.toLowerCase().replace('_', '-').startsWith(`${language}-`)) ??
    voices.find((voice) => voice.lang.toLowerCase() === language)
  );
}

export function speakWithBrowser(text: string, locale: string, voiceName = '', rate = 1): Promise<void> {
  return new Promise((resolve) => {
    if (!('speechSynthesis' in window)) {
      resolve();
      return;
    }
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = locale;
    utterance.rate = rate;
    const voice = pickVoice(locale, voiceName);
    if (voice) utterance.voice = voice;
    utterance.onend = () => resolve();
    utterance.onerror = () => resolve();
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(utterance);
  });
}

export interface VoiceOptions {
  locale: string;
  voice?: string;
  rate?: number;
}

export async function playText(target: string, text: string, options: VoiceOptions): Promise<void> {
  const clean = text.trim();
  if (!clean) return;
  stopAudio();
  const url = await fetchAudioUrl(target, clean);
  if (url) {
    const audio = new Audio(url);
    audio.playbackRate = options.rate ?? 1;
    current = audio;
    try {
      await audio.play();
      await new Promise<void>((resolve) => {
        audio.onended = () => resolve();
        audio.onpause = () => resolve();
      });
      return;
    } catch {
      // Autoplay blocked or unsupported format: fall back to speech synthesis.
    }
  }
  await speakWithBrowser(clean, options.locale, options.voice, options.rate);
}

// Voices load asynchronously in some browsers.
if ('speechSynthesis' in window) {
  window.speechSynthesis.getVoices();
}
